version: "3"

services:
  client:
    image: client
    build: ./frontend/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern_app
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    image: server
    build: ./backend/
    ports:
      - "3001:3001"
    networks:
      - mern_app
    volumes:
      - ./backend/:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6-xenial
    ports:
      - "27017:27017"
    networks:
      - mern_app
    volumes:
      - mongo_data:/data/db

networks:
  mern_app:
    driver: bridge

volumes:
  mongo_data:
    driver: local
