name: Publish the latest development docker images

on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
      USERNAME: ${{ GITHUB.ACTOR }}
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{GITHUB.REPOSITORY}}

jobs:
  Backend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Authenticate docker for github
        run: docker login https://docker.pkg.github.com -u $USERNAME -p $PASSWORD
      - name: Build backend docker image
        run: docker build -t docker.pkg.github.com/$REPO/server ./backend
      - name: Push server image to github package repository
        run: docker push docker.pkg.github.com/$REPO/server
      
  Frontend:    
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Authenticate docker for github
        run: docker login https://docker.pkg.github.com -u $USERNAME -p $PASSWORD
      - name: Build frontend docker image
        run: docker build -t docker.pkg.github.com/$REPO/client ./frontend
      - name: Push client image to github package repository
        run: docker push docker.pkg.github.com/$REPO/client
